#!/bin/bash

startTime=/tmp/yt-start-time.log

if [[ -f "$startTime" ]]; then
	read -r _ _ epoch < "$startTime"

	currentEpoch=$(date +%s)
	duration=$((currentEpoch - epoch))
	hours=$((duration / 3600))
	minutes=$(((duration % 3600) / 60))
	# seconds=$((duration % 60))
	printf "%17s %02d:%02d\n" "uptime:" "$hours" "$minutes"
fi

printf "%17s %s\n" "pkgTemp:" "$(sensors | awk -F'[ +]+' '/Package id 0:/ {print $4; exit}')"

yt --recent
echo

df -h /dev/sda1 --output=source,target,avail
echo

yt -s
echo

# ytpath is an env var. Where you want files saved.
# fd -e list -x sh -c 'echo -e "\033[33m$1\033[0m"; cat "$1" | tail -n +2; echo' _ {}		# works
find "$YTPATH" -type f -name "*.list" -exec sh -c 'echo -e "\033[33m$1\033[0m"; cat "$1" | tail -n +2; echo' _ {} \;
