#!/bin/bash

source "$HOME"/.scripts/std 2>/dev/null
startTime=$(date +%s.%N)

script="$(basename "$0")"
dbPath=$ytPath		#env var
file=$1
ARGC=$#
declare -a videos
declare -a metadata
matchingVideos=()

tmpfile=$(mktemp)	# tmp file for the matching vids
cachedCnt=0
processedCnt=0

format=$'General;%OverallBitRate/String%,%Duration/String2%,%Duration%,%FileSize/String%,%CompleteName%,%Format%,\n'
format+='Video;%Width%x%Height%,%FrameRate%fps,%CodecID%,'

usage() {
	cat <<-DOC
	Usage: $script [regex]

	Uses a fd RE2 regex to search for video files. Trims input trailing slashes.
	Prints out metadata (bit rate, duration, size, filename, resolution, fps, codec).

	Requires: fd, mpv, mediainfo

	Examples:
        $script peach
        $script https://domain.com/peach/
        $script -d 600 peach	# videos longer than 600s (10 mins)
DOC
}

calcEndTime() {
	endTime=$(date +%s.%N)
	elapsedTime=$(echo "$endTime - $startTime" | bc)
	printf "Time elapsed: %.3f seconds\n" $elapsedTime >&2
}

requires() {
	if ! command -v "$1" &>/dev/null; then
		echo "Requires $1"
		exit 1
	fi
}

retypeCMD() {
	interactiveShell=$(ps -o comm= -p $PPID)

	if [[ $interactiveShell == zsh ]]; then
		xdotool type "$(basename ${BASH_SOURCE}) " &>/dev/null && exec zsh
	elif [[ $interactiveShell == bash ]]; then
		xdotool type "$(basename ${BASH_SOURCE}) " &>/dev/null & disown
	fi
}

getName() {
	if [[ $ARGC -gt 1 ]]; then
		file=$1
	fi

	if [[ $file =~ ^https?:// ]]; then
		name=$(basename "$file")
	else
		name="${file#/}"
		name="${name%/}"
	fi
	echo "$name"
}

basic() {
	mapfile -t videos < <(fd -e mp4 -t f "$name")

	for video in "${videos[@]}"; do
		hash=$(head -c 1M "$video" | sha256sum)
		hash=${hash%% *}
		username="${video%% *}"		# Remove everything after first space

		cachedMetadata=$(sqlite3 "$dbFile" "select metadata from videos where hash = '$hash'" 2>/dev/null)

		if [[ -n "$cachedMetadata" ]]; then
			echo "$cachedMetadata" >> "$tmpfile"
			((cachedCnt++))
		else
			info=$(mediainfo --Output="$format" "$video")
			((processedCnt++))
			echo "$info" >> "$tmpfile"
		fi

		matchingVideos+=("$video")
	done
}

filterDuration() {
	minDuration=$1
	name=$2

	dbFile="$dbPath/videos.db"

	if [[ ! -f "$dbFile" ]]; then
		sqlite3 "$dbFile" "CREATE TABLE videos (
		   hash TEXT PRIMARY KEY,
		   file TEXT,
		   username TEXT,
		   duration INTEGER,
		   metadata TEXT
		);" 2>/dev/null
	fi

	mapfile -t videos < <(fd -e mp4 -t f "$name")

	for video in "${videos[@]}"; do
		hash=$(head -c 1M "$video" | sha256sum)
		hash=${hash%% *}
		username="${video%% *}"		# Remove everything after first space

		# Check if in cache
		cachedMetadata=$(sqlite3 "$dbFile" "select metadata from videos where hash = '$hash'" 2>/dev/null)

		if [[ -n "$cachedMetadata" ]]; then
			# Get duration from cache to check if it meets minimum duration
			cacheDur=$(sqlite3 "$dbFile" "select duration from videos where hash = '$hash'" 2>/dev/null)
			((cachedCnt++))

			if ((cacheDur >= minDuration)); then
				echo "$cachedMetadata" >> "$tmpfile"
				matchingVideos+=("$video")
			fi
		else
			# Process file
			info=$(mediainfo --Output="$format" "$video")
			IFS="," read -r _ _ rawDuration _ <<< "$info"
			dur=${rawDuration%.*}			# remove decimal
			[[ -z "$dur" ]] && continue		# skip empty results
			((dur /= 1000))					# convert to seconds
			((processedCnt++))

			sqlite3 "$dbFile" "insert or replace into videos \
				(hash, file, username, duration, metadata) \
				values ('$hash', '$video', '$username', $dur, '$info')" 2>/dev/null

			if ((dur >= minDuration)); then
				echo "$info" >> "$tmpfile"
				matchingVideos+=("$video")
			fi
		fi
	done

	echo "Used cache: $cachedCnt files, Processed: $processedCnt files"
	echo -e "Found ${#matchingVideos[@]} videos with duration >= ${minDuration}s \n"
}

if [[ $# -eq 0 ]]; then
	echo "Provide at least one argument."
	exit 1
fi

requires fd
requires mediainfo
requires mpv
trap retypeCMD EXIT

while [ $# -gt 0 ]; do
	case $1 in
	-d | --duration)
		shift
		name=$(getName "$2")
		filterDuration "$1" "$name"
		break
		;;
	-h | --help)
		usage
		exit
		;;
	*)
		name=$(getName "$1")
		basic "$name"
		;;
	esac
	shift
done

mapfile -t metadata < "$tmpfile"
calcEndTime

if [[ ${#metadata[@]} -gt 0 ]]; then
	echo -e "Found ${#metadata[@]} videos\n"
	column -t -s ',' "$tmpfile"
	echo
	read -rp "Open files? [y,Y] "
	if [[ $REPLY =~ ^[yY]$ ]]; then
		mpv "${matchingVideos[@]}" &>/dev/null &
	fi
fi
