#!/bin/bash

#https://docs.kde.org/trunk5/en/konsole/konsole/command-line-options.html

# Run with `yt-rec && exit`. ytpath is an env var. Where you want files saved.

saveDir="$ytpath"
tabsFromFile="/run/media/erik/storage/vuze/megaDL/konsole.txt"

cmd=$1
cmd=${cmd:-yt }

fromFile() {
	konsole -p tabtitle='yt' --separate --tabs-from-file "$tabsFromFile" &
}

runUI() {
	if ! pgrep -f "alacritty.*--title yt" > /dev/null; then
		alacritty --config-file ~/scratch/alacritty-yt.toml \
			--title yt \
			--command /bin/bash -c \
			'watch -d -c ui' & disown
	fi
}

if [ "$1" = "-ui" ]; then
	runUI
	exit
fi

echo "$(date '+%Y-%m-%d %H:%M:%S') $(date +%s)" > /tmp/yt-start-time.log

runUI

for ((i = 1; i <= 19; i++)); do
	# konsole -p tabtitle="ch$i" --workdir="$saveDir" --new-tab -e "bash -c 'xdotool type \"$cmd\" && exec zsh'"
	konsole -p tabtitle="ch$i" --workdir="$saveDir" --new-tab -e "bash -c '{ sleep 0.1; xdotool type \"$cmd\" ;} & disown; exec zsh'"
done

konsole -p tabtitle="insert" --workdir="$saveDir" --new-tab -e "bash -c '{ sleep 0.1; xdotool type \"insert \" ;} & disown; exec zsh'"
konsole -p tabtitle="fd" --workdir="$saveDir" --new-tab -e "bash -c '{ sleep 0.1; xdotool type \"fd \" ;} & disown; exec zsh'"
konsole -p tabtitle="mpv" --workdir="$saveDir" --new-tab -e "bash -c '{ sleep 0.1; xdotool type \"mpv \" ;} & disown; exec zsh'"
konsole -p tabtitle="vidinfo" --workdir="$saveDir" --new-tab -e "bash -c '{ sleep 0.1; xdotool type \"vidinfo \" ;} & disown; exec zsh'"
konsole -p tabtitle="tmp" --workdir="$saveDir" --new-tab -e "bash -c '{ sleep 0.1; xdotool type \"yt --pauseall \" ;} & disown; exec zsh'"
konsole -p tabtitle='yt' --workdir="$saveDir" --new-tab -e "bash -c 'exit'"
